### ISSUE TITLE
Unable to locate package php7.2-mcrypt

### ISSUE THREAD

**Issue by RafikFarhad** [scdnlab/easy-ubuntu-dev-setup#9]
https://github.com/scdnlab/easy-ubuntu-dev-setup/blob/74fe066bb4ba7d2784349e356e6195b7dd5b582c/lemp_setup.sh#L25

p7.2-mysql php7.2-curl php7.2-json php7.2-cgi libphp7.2-embed libapache2-mod-php7.2 php7.2-zip php7.2-mcrypt php7.2-mbstring php7.2-xml php7.2-intl
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package php7.2-mcrypt
E: Couldn't find any package by glob 'php7.2-mcrypt'
E: Couldn't find any package by regex 'php7.2-mcrypt'

**Comment by ivan-technocrat** [comment]
PHP mcrypt library is deprecated and will be removed in PHP 7.2
http://php.net/manual/en/intro.mcrypt.php

**Comment by paulocastroo** [comment]
I need mcrypt to composer install a dependency, is there a workaround?

**Comment by RafikFarhad** [comment]
Hello @paulocastroo ,
Here is a way to use mcrypt in php 7.2 .
------
https://gist.github.com/arzzen/1209aa4a430bd95db3090a3399e6c35f
------
I've not tested this specific method, but I'm using mcrypt for my older projects of laravel in PHP7.2
Let me know if this works.

**Comment by ThakurPradeep** [comment]
Use below link it's work perfectly.

https://gist.github.com/arzzen/1209aa4a430bd95db3090a3399e6c35f#gistcomment-2690896
